// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.Entities;

namespace webapi.Migrations.Banco
{
    [DbContext(typeof(BancoContext))]
    [Migration("20180822131020_clienteAtivo")]
    partial class clienteAtivo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("webapi.Models.Cliente", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("ativo");

                    b.Property<DateTime>("dataCriado");

                    b.Property<int>("diaVencimento");

                    b.Property<string>("email");

                    b.Property<Guid>("idUser");

                    b.Property<string>("login");

                    b.Property<string>("nome");

                    b.Property<string>("senha");

                    b.Property<string>("telefone");

                    b.Property<decimal>("valorCobrado");

                    b.HasKey("id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("webapi.Models.Financeiro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dataBaixa");

                    b.Property<DateTime>("dataLancamento");

                    b.Property<DateTime>("dataVencimento");

                    b.Property<Guid>("idCliente");

                    b.Property<Guid>("idUser");

                    b.Property<int>("origemPagamento");

                    b.Property<decimal>("valorCobrado");

                    b.Property<decimal>("valorLogin");

                    b.HasKey("Id");

                    b.ToTable("Financeiro");
                });

            modelBuilder.Entity("webapi.Models.PagSeguro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("code_reference");

                    b.Property<Guid>("financeiroId");

                    b.HasKey("Id");

                    b.ToTable("PagSeguro");
                });

            modelBuilder.Entity("webapi.Models.Revendedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("idUser");

                    b.Property<decimal>("valorLogin");

                    b.HasKey("Id");

                    b.ToTable("Revendedor");
                });
#pragma warning restore 612, 618
        }
    }
}
